### ISSUE TITLE
missing Knurlie.svg

### ISSUE THREAD

**Issue by davephillips** [chrisbeckstrom/Beckstrom_Research_Rack#1]
Fedora 23 Linux
Rack 0.5.x

Hi Chris, Nice start on your modules, they build and load fine on my system. However, your res directory appears to be missing a file:

[warning] Failed to load SVG ./plugins/chrisbeckstrom-plugins/res/Knurlie.svg

Best regards,
Dave Phillips

**Comment by chrisbeckstrom** [comment]
Hey @davephillips, sorry for the LONG delay in getting back to you! I really appreciate the help!
I just redid most everything to work with 0.6, and in the process I removed what I think was causing the `Knurlie.svg` issue. Thanks!
